# Generated by Django 3.1.2 on 2021-02-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=122)),
                ('name', models.CharField(max_length=112)),
                ('country', models.CharField(max_length=112)),
                ('massage', models.CharField(max_length=500)),
            ],
        ),
    ]
